# Generated by Django 5.2 on 2026-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_post_created_at_post_published_at_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
