# Generated by Django 5.2 on 2026-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_alter_post_options_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='app2/default.jpg', upload_to='app2/'),
        ),
    ]
