# Generated by Django 5.2 on 2026-06-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='app2.category'),
        ),
    ]
