# Generated by Django 5.2 on 2026-07-06 07:35

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_alter_post_created_at_alter_post_published_at_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
