# Generated by Django 5.2 on 2026-07-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
