# Generated by Django 5.2 on 2026-07-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
